### PR TITLE
Brendancol nafix ccc mods

### LINKED ISSUE #322: CCC UI: Default value for non-corp entity tax rate
We have the default rate on non-corporate entities shown to be 0.35.  Is there a way to make this change conditional on other inputs?  In particular, to have the default rate be 0.0, but if the non-corporate entity level tax indicator is checked, then this default is changed to 0.35 (or whatever is entered in the corporate tax rate box above)?  

As it stands, I can see people asking questions like "why do you have the default rate on NC entities at 0.35 when it is 0.0?"  But I like the idea that if one wanted to institute a comprehensive business income tax, the default is to take all entities at the same rate.

### PR DESCRIPTION
**Pull request by talumbau**
Small update to #345. Requested fixes noted in commit history. Resolves #322

### CODE REVIEW

**Comment by talumbau** [comment]
@MattHJensen @jdebacker here is what my PR adds to @brendancol 's #345 

screen shot 2016-09-30 at 11 19 42 am

Does that look right?

**Comment by MattHJensen** [comment]
@talumbau That looks right to me. Regarding the non-corporate entity level tax, if the switch is still in B-Tax, the (hidden) default for webapp will need to be `True`, right? So the entity level tax is turned on, but the default value is 0. ( I don't entirely understand how these changes can happen w/o any changes to B-Tax, but that's because I haven't been following ccc development closely. )

**Comment by talumbau** [comment]
Ah @MattHJensen good call. I just did an additional fix and ran a test locally. Here are the user-provided modifications given to B-Tax when I just change corporate income tax rate to 0.38:

```
{'btax_depr_10yr_tax_Switch': [False], 'btax_depr_3yr_gds_Switch': [False], 'btax_betr_corp': [0.38], 'btax_depr_5yr_tax_Switch': [False], 'btax_depr_allyr_tax_Switch': [False], 'btax_depr_5yr_gds_Switch': [False], 'btax_depr_15yr_tax_Switch': [False], '_state': <django.db.models.base.ModelState object at 0x10ff83a50>, 'btax_depr_25yr_gds_Switch': [False], 'creation_date': datetime.datetime(2015, 1, 1, 0, 0), 'btax_depr_5yr_ads_Switch': [False], 'btax_depr_5yr': [False], 'btax_betr_entity_Switch': [True], 'btax_depr_3yr_tax_Switch': [False], 'btax_depr_25yr_tax_Switch': [False], 'id': 22, 'btax_betr_pass': [0.0], 'btax_depr_27_5yr': [False], 'btax_depr_39yr_gds_Switch': [False], 'first_year': 2016, 'btax_depr_39yr': [False], 'btax_depr_10yr': [False], 'btax_depr_20yr_gds_Switch': [False], 'btax_depr_3yr_ads_Switch': [False], 'btax_depr_25yr_ads_Switch': [False], 'btax_depr_15yr_ads_Switch': [False], 'btax_depr_7yr_ads_Switch': [False], 'btax_depr_20yr_ads_Switch': [False], 'btax_depr_15yr': [False], 'btax_depr_27_5yr_tax_Switch': [False], 'btax_depr_39yr_ads_Switch': [False], 'btax_depr_allyr_gds_Switch': [False], 'btax_depr_15yr_gds_Switch': [False], 'btax_depr_20yr': [False], 'btax_depr_10yr_ads_Switch': [False], 'btax_depr_25yr': [False], 'btax_depr_27_5yr_ads_Switch': [False], 'btax_depr_39yr_tax_Switch': [False], 'btax_depr_27_5yr_gds_Switch': [False], 'btax_depr_3yr': [False], 'btax_depr_7yr_gds_Switch': [False], 'btax_depr_20yr_tax_Switch': [False], 'btax_depr_7yr': [False], 'btax_depr_10yr_gds_Switch': [False], 'btax_depr_7yr_tax_Switch': [False], 'btax_depr_allyr_ads_Switch': [False]}
```

Note that I get `btax_betr_corp` set to 0.38 (as expected), but also that `btax_betr_entity_Switch` is True and `btax_betr_entity_pass` is 0.0. So I think that should do it. @jdebacker can you confirm?

**Comment by talumbau** [comment]
Since these are B-Tax specific changes and unlikely to disrupt current features of TaxBrain, merging for now.

**Pull request merged**
