### PR TITLE
Remove AMT capital gains input; copy over rt CG

### PR DESCRIPTION
**Pull request by talumbau**
- Get rid of the AMT capital gains input section
 - Copy over the Regular Tax Capital Gains section to be
   AMT CG values as well

### CODE REVIEW

**Comment by talumbau** [comment]
first part of #340

**Comment by talumbau** [comment]
- [ ] Removed AMT CG section
- [ ] Regular Tax CG parameters copy to AMT CG parameters
- [ ] II Tax parameters copied to Pass Through parameters

**Comment by talumbau** [comment]
This PR depends on the latest changes to Tax-Calculator and so won't pass until we release a new version (version 0.6.7 of TC)

**Comment by talumbau** [comment]
@MattHJensen I can release 0.6.7 of TC whenever is convenient to get this in master.

**Comment by MattHJensen** [comment]
Thanks a lot @talumbau.

> @MattHJensen I can release 0.6.7 of TC whenever is convenient to get this in master.

Let's do it.

**Pull request merged**
