### PR TITLE
Better formating for file-based reuslts pages

### PR DESCRIPTION
**Pull request by talumbau**
- monospace font for reform file text
 - white space respected in text from file
 - More descriptive/appropriate text on file-based reform input page

### CODE REVIEW

**Comment by talumbau** [comment]
Resolves #358 In particular, the text for the file is displayed in a monospace font with whitespace respected:

screen shot 2016-10-14 at 3 29 09 pm

cc @martinholmer @MattHJensen

**Comment by martinholmer** [comment]
@talumbau,  Thanks so much for the improvements in TaxBrain pull request #365.

**Comment by martinholmer** [comment]
@talumbau,  I tried using the `taxbrain/file/` page, but it didn't seem like the changes in TaxBrain #365 were active yet.  When do you expect #365 changes to be active on the website?

**Comment by talumbau** [comment]
Hmm... I'm not sure what you mean. When I go to www.ospc.org/taxbrain/file, I see the following:

 - text changes on the input page based on suggestions in #358, including the link the `REFORMS.md` file on Github
 - the desired text on the results page before the JSON parameters are displayed
 - monospace font and white space respected on display of file text.

For example, this reform:

http://www.ospc.org/taxbrain/6433/

So can you describe in what way the processing on www.ospc.org/taxbrain/file does not reflect what is described in #365 ?

**Comment by martinholmer** [comment]
@talumbau,  Look at this page (which doesn't have the spacing right):

http://www.ospc.org/taxbrain/6434/

**Comment by talumbau** [comment]
Ah, so the monospace font and respecting whitespace does not occur on error reporting. I will create an issue to fix this.

**Pull request merged**
