### PR TITLE
Updates to Model Fields

### PR DESCRIPTION
**Pull request by brittainhard**

### CODE REVIEW

**Comment by talumbau** [comment]
Oh it looks like everything is an `AddField` for the migration. That's good. I thought certain names changed. @MattHJensen is it the case that the changes in https://github.com/open-source-economics/Tax-Calculator/pull/1109 were just additions to the current_law_policy.json? Did any field change names?

**Comment by MattHJensen** [comment]
That's right, @talumbau. Here's the relevant comment: https://github.com/open-source-economics/Tax-Calculator/pull/1109#issuecomment-267736621

**Comment by brittainhard** [comment]
I'l fix that quickly.

**Comment by talumbau** [comment]
Yes, I'm looking at it closely because there are a number of changes. It actually looks good to me, except for the STD_Dep parameter. It appears to be a multi-valued parameter in current_law_policy.json, but in this PR, it's still the single value `STD_Dep`. I think `STD_Dep` should be removed and  `STD_Dep_0`, `STD_Dep_1`, `STD_Dep_2`, `STD_Dep_3`,  should be added along with `STD_Dep_cpi` as a `NullBooleanField` like the other CPI flags. Does that sound right @MattHJensen ?

**Comment by MattHJensen** [comment]
@talumbau, `_STD_Dep` has a single value per year (unlike `_STD`)

https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/current_law_policy.json#L429-L434

**Comment by talumbau** [comment]
Oops, my fault. Right, so this PR is correct with `STD_Dep` as just a single attribute on the model.

**Comment by brittainhard** [comment]
@talumbau @MattHJensen do you think this is ready to merge?

**Comment by talumbau** [comment]
I'll run this locally, including the migration to see how it goes.

**Comment by talumbau** [comment]
Ran this locally. Migration looked good. Let's merge and I will push up to production tonight

**Pull request merged**
