### PR TITLE
Fast calculation

### PR DESCRIPTION
**Pull request by talumbau**
Partial fulfillment of #274 

Needs PRs https://github.com/open-source-economics/Tax-Calculator/pull/844 and a PR on https://github.com/OpenSourcePolicyCenter/deploy in order to work successfully

Also needs button to trigger "small data" calculation.

### CODE REVIEW

**Comment by talumbau** [comment]
@feenberg @MattHJensen here is what the new button looks like on the TaxBrain page:

screen shot 2016-08-05 at 2 14 27 pm

**Comment by talumbau** [comment]
@mistakevin please review the less file changes and input form template changes - thanks!

**Comment by talumbau** [comment]
this PR depends on:

https://github.com/OpenSourcePolicyCenter/deploy/pull/4/files

and

https://github.com/open-source-economics/Tax-Calculator/pull/844

**Comment by mistakevin** [comment]
LGTM

**Pull request merged**
