### PR TITLE
Unicode issue 232

### LINKED ISSUE #232: TaxBrain handling of the * notation for delayed reform implementation
Using TaxBrain version 0.6.3.8b7f3b, I try to double the 0.9% Additional Medicare tax rate beginning in 2018 (when the TaxBrain start year is 2016) by entering the following in that text box:
```
*,*,0.018
```
When I click on `Show me the results!`, I immediately get a new page that says:
```
500 Internal Server Error!
```
And there is no further explanation.  Did I do something wrong?  Or, is this a bug in TaxBrain?

@talumbau

### PR DESCRIPTION
**Pull request by talumbau**
resolves #232

### CODE REVIEW

**Comment by martinholmer** [comment]
T.J., Thanks for the quick fix.

**Comment by martinholmer** [comment]
@talumbau,  When will pull request #233 be incorporated in the publicly-available TaxBrain?

**Comment by talumbau** [comment]
@martinholmer did you not see [my comment](https://github.com/OpenSourcePolicyCenter/webapp-public/issues/232#issuecomment-217648658) from Saturday? #233 was live on TaxBrain as of Saturday morning. #236 handles the issue you raised in #235 which involves wildcards with multi-valued parameters. Your comments on #235 led me to believe that the problem you experienced in #232 had been resolved. So, to be more specific, the fix for specifying a wildcard for something like the Additional Medicare FICA Threshold will be pushed by end of day. As far as I know, there are no current issues for specifying wildcards for single-valued parameters. Do I understand everything correctly?

**Comment by martinholmer** [comment]
Sorry for the confusion in my question.
@talumbau said:
> Do I understand everything correctly?

Yes.  Thanks for the quick pace of fixes.  I'll test TaxBrain again tomorrow.

**Pull request merged**
