### PR TITLE
Fix /ccc row ordering issues: 385, 386, 387, 388

### PR DESCRIPTION
**Pull request by PeterDSteinberg**
This fixes issues related to row ordering on /ccc results tables and gets rid of the extra footer info.

Here is the new industry look:
screen shot 2016-10-28 at 12 16 01 pm

This shows the minor headings "Durable goods" and "Nondurable goods" inside "Manufacturing" section:
screen shot 2016-10-28 at 12 16 17 pm

And here's the fixed footer:
screen shot 2016-10-28 at 12 16 24 pm

### CODE REVIEW

**Comment by MattHJensen** [comment]
@PeterDSteinberg @jdebacker, in all situations like the one below, the second line should replace the first line, right? 

image

**Comment by jdebacker** [comment]
Matt is right. 

Cc @peterdsteinberg

**Comment by PeterDSteinberg** [comment]
ok will fix the double-summary-row issue.

**Comment by PeterDSteinberg** [comment]
Last commit removes the double-summary row issue:

screen shot 2016-10-28 at 1 07 29 pm

**Comment by jdebacker** [comment]
LGTM

**Pull request merged**
