### PR TITLE
Remove JSON Endpoint

### LINKED ISSUE #355: remove JSON text field input page
the `/json` page has been removed in favor of `/file`. See #312, #353 for details.

### PR DESCRIPTION
**Pull request by brittainhard**
Closes #355

### CODE REVIEW

**Comment by talumbau** [comment]
@brittainhard I did a global search for "START YEAR" (case insensitive). I think there are more places to change. It looks like there are hard coded "2016"s in there, but the desire was to make everything based on a global environment variable, as shown here:

https://github.com/OpenSourcePolicyCenter/webapp-public/blob/a37f4e50854d2b393e72e36405cd1c26ceae18bf/webapp/apps/taxbrain/helpers.py#L18

Let's change the default value to '2017' in the absence of any specified start year at that line.

**Comment by brittainhard** [comment]
@talumbau this should be fixed in #442

**Comment by talumbau** [comment]
Oops you are right. The above comment was fro #442.

**Comment by talumbau** [comment]
ok this one looks good. merging.

**Pull request merged**
