### PR TITLE
UI Generation based on current_law_policy

### PR DESCRIPTION
**Pull request by brittainhard**

### CODE REVIEW

**Comment by talumbau** [comment]
@brittainhard when this is ready, coordinate with @MattHJensen to push to the test application for testing first.

**Comment by MattHJensen** [comment]
@brittainhard, how is #450 looking?

**Comment by brittainhard** [comment]
@MattHJensen sorry for the lack of communication. This is ready for review. It makes some substantial changes.

@PeterDSteinberg are you available to do some manual testing?

**Comment by MattHJensen** [comment]
@brittanhard, that's great. It would be easiest for me to review through manual inspection on the test site.

**Comment by brittainhard** [comment]
@MattHJensen i'll work with Peter today to get this PR on the test app.

**Comment by MattHJensen** [comment]
@brittainhard, these two sets of parameters are a bit off. Besides the other formatting issues, the check boxes are right for both. 

image

image

**Comment by brittainhard** [comment]
Thanks @MattHJensen ill have a fix ready tomorrow.

**Comment by brittainhard** [comment]
@MattHJensen I need to work on getting the tests to pass before we merge this. Shouldn't take too long.

**Comment by brittainhard** [comment]
@MattHJensen this is ready to merge.

**Comment by MattHJensen** [comment]
+1 Fire when ready.

**Pull request merged**
