### PR TITLE
Refine sign in flow

### PR DESCRIPTION
**Pull request by kevincolten**

### CODE REVIEW

**Comment by talumbau** [comment]
The two emails seem too similar to me. Text when registering for the page:

```
Welcome! 

Thank you for registering with ospc.org. This is the best way to stay up to date on 
the latest news from the Open Source Policy Center. We also invite you to beta test 
the TaxBrain webapp. 

Username: g10391160 
Password: taxbrain 
```

Text for signing up for mailing list:

```
Welcome! 

Thank you for registering with ospc.org. This is the best way to stay up to date on 
the latest news from the Open Source Policy Center. We also invite you to beta test 
the TaxBrain webapp. 
```

I think for the "sign up" action, the email should say something like "Thanks for signing up for the OSPC mailing list! This is the best way to stay up to date on the latest news from the Open Source Policy Center"

I think the for "register" action, the email should say something like "Thanks for registering! Keep track of the account info below because you'll need it log in to ospc.org. We'll also keep you informed about the latest news from the Open Source Policy Center." (because the "register" action includes getting on the mailing list, it just also gives you an account).

**Comment by talumbau** [comment]
I realized while reviewing this PR and #3 that I don't actually understand the goals we are trying to achieve. I think it's best to disregard what I've written above until I have more clarity

**Comment by talumbau** [comment]
One thing that's true about this PR is that we have 100% removed the confirmation email link, which seems wrong. We definitely want a confirmation email on signing up via email.

**Comment by mistakevin** [comment]
@talumbau This has been updated to match the current specs as I understand them. It is important to note that subscribers and registered users are still in separate tables.

**Comment by talumbau** [comment]
Trying this PR out on latest master. The interactions are simple, which is good, but they have left out important functionality. The following is based on details gleaned from a conversation with @MattHJensen. The new terminology is my own suggestion.

This PR (and the relevant code in current master) are in support of two features: signing up for the newsletter and registering with a username, password, and email address to be a registered user of TaxBrain. We will now use the following terms for these interactions:

 - one *subscribes* to the newsletter
 - one *registers* for the website

Therefore, all buttons that say "SIGN UP" should be changed to say "SUBSCRIBE". "SIGN UP" could indicate either interaction.

1. The *subscribe* flow is:  put in email address -> get email with confirmation link -> click link and go to page that confirms subscribing. This PR has removed the confirmation link -> confirmed subscribe part of the interaction. It should go back in.

2. The *register* flow is: put in username/password/email address -> get email with username/password in it and confirmation link -> click link and go to page that confirms registering. This PR has removed the confirmation link -> confirmed registration part of the interaction. It should go back in.

I think with those fixes this would be good to go.

**Comment by talumbau** [comment]
Actually, let me clarify. The "SIGN UP" button at the top of the site should be changed to "REGISTER" and the "SIGN UP" button next to the "Enter email to subscribe" should be changed to "SUBSCRIBE". That will distinguish to behaviors.

**Comment by mistakevin** [comment]
@talumbau updated buttons

**Comment by talumbau** [comment]
@mistakevin ok great thanks. It looks like the remaining tasks on this PR then are:

- put the confirmation link back in on the *register* interaction

- put the confirmation link back in on the *subscribe* interaction

**Comment by mistakevin** [comment]
@talumbau You mean the confirmation links in the emails? Are they not showing up?

**Comment by talumbau** [comment]
Correct. they are not showing up with this PR.

**Comment by mistakevin** [comment]
I'm getting both of them. Is the spec something else?

screen shot 2015-10-04 at 8 54 07 pm
screen shot 2015-10-04 at 8 55 30 pm

**Comment by mistakevin** [comment]
Now resolves Issue https://github.com/OpenSourcePolicyCenter/webapp-public/issues/11

**Comment by brendancol** [comment]
@talumbau closing as stale

**Pull request closed without merging**
