### PR TITLE
View for border adjustment plot

### LINKED ISSUE #470: Embed iframe for border adjustment calculator at ospc.org/bac
https://ospc.shinyapps.io/border-adjustment-calculator/

### PR DESCRIPTION
**Pull request by brittainhard**
Closes #470

### CODE REVIEW

**Comment by brittainhard** [comment]
@MattHJensen this is ready for review.

**Comment by MattHJensen** [comment]
Cool! Looks good to deploy to the test app.

**Comment by brittainhard** [comment]
@MattHJensen its at https://ospc-taxes7.herokuapp.com/gallery/

**Comment by MattHJensen** [comment]
Looks great.

**Pull request merged**
