### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by DoraSzasz**
git clone git@github.com:OpenSourcePolicyCenter/webapp.git does not exist.
Changed to: git@github.com:OpenSourcePolicyCenter/webapp-public.git

### CODE REVIEW

**Comment by brittainhard** [comment]
Not sure why this is failing tests, but its just a change in the readme, so no need to hold it up.

**Comment by martinholmer** [comment]
@brittainhard said about PR #583:
> Not sure why this is failing tests

Everything seems to go fine with the tests until you tried to get taxcalc 0.9.0 package,
which FAILED, and then this command `python manage.py syncdb --noinput` FAILED.

When I look on anaconda.org, I see all 15 taxcalc 0.9.0 packages, so the package you want is there.

Here's the edited log:
```
$ python --version
Python 2.7.9
$ pip --version
[snip]
install.1
[snip]
install.2
[snip]
install.3
0.00s$ export PATH="$HOME/miniconda/bin:$PATH"
install.4
[snip]
Fetching package metadata: ........
Solving package specifications: .
Error:  Package missing in current linux-64 channels: 
  - taxcalc ==0.9.0
You can search for this package on anaconda.org with
    anaconda search -t conda taxcalc ==0.9.0
You may need to install the anaconda-client command line client with
    conda install anaconda-client
FAILED
install.6
0.00s$ popd
~/build/OpenSourcePolicyCenter/webapp-public
install.7
0.27s$ source activate aei_dropq
discarding /home/travis/miniconda/bin from PATH
prepending /home/travis/miniconda/envs/aei_dropq/bin to PATH
0.02s$ python manage.py syncdb --noinput
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management
The command "python manage.py syncdb --noinput" failed and exited with 1 during .
Your build has been stopped.
```

@hdoupe

**Comment by talumbau** [comment]
Not sure about this specific PR, but in general, pull requests from contributors not in the right Github organization will not be able to pass all of the tests. That is because there are certain private variables in the Travis CI test environment that are only visible to users in the proper Github org. @brittainhard this may have changed but there was the way it was setup previously. This typically isn't a big deal but for more involved PRs, you will probably want to do a PR against the user's PR or add the contributor to the proper Github org.

**Comment by brittainhard** [comment]
Thanks @talumbau i'll definitely keep that in mind next time we run into something like this.

**Pull request merged**
