### PR TITLE
Use checkboxes for boolean parameters.

### LINKED ISSUE #504: _ALD_InvInc_ec_base_RyanBrady should be checkbox instead of 1/0
As a rule, we can use checkboxes when parameters are boolean in current_law_policy.json. 

image

@brittainhard

### LINKED ISSUE #520: NIIT parameter is Boolean
The `_NIIT_PT_taxed` parameter is Boolean in Tax-Calculator, while that is not the case in TaxBrain, as indicated in the screen shot. This seems a bug to me.

cc @MattHJensen @brittainhard 

screen shot 2017-04-04 at 1 37 57 pm

### PR DESCRIPTION
**Pull request by brittainhard**
Closes #520 
Closes #504

### CODE REVIEW

**Comment by brittainhard** [comment]
@MattHJensen do you wanna take a look so I can merge it?

**Comment by MattHJensen** [comment]
Could you push to the test app?

**Comment by brittainhard** [comment]
@MattHJensen its up on the test app.

**Comment by MattHJensen** [comment]
Doesn't seem like reforms to these parameters changes results. Also, when I check a box, run results, and then click edit parameters, the box is unchecked.

**Comment by brittainhard** [comment]
I'll take a second look at it.

**Comment by brittainhard** [comment]
Closing, merging code with #551

**Pull request closed without merging**
