### PR TITLE
Added Current Law, Reform and Change to fiscal tables to TaxBrain table-builder

### PR DESCRIPTION
**Pull request by brendancol**
#380 

Note: this PR is still WIP and has mock data located:
https://github.com/OpenSourcePolicyCenter/webapp-public/blob/b3ceb37718cd1cb15e4df0e224f8139379cb6f09/static/js/taxbrain-tablebuilder.js#L592-L603

screen shot 2016-11-15 at 10 49 40 pm

### CODE REVIEW

**Comment by brendancol** [comment]
@talumbau Do you know if the Travis CI error above is just taxcalc version issue?  I'm seeing a bunch of `KeyError: u'CTC_new_refund_limit_payroll_rt'`

**Comment by brendancol** [comment]
@talumbau This PR uses mock data to achieve the new table layout.  Instead of `fiscal_tots`, and you name the keys, `fiscal_currentlaw`, `fiscal_reform`, and `fiscal_change`?

**Comment by talumbau** [comment]
@brendancol please see https://github.com/OpenSourcePolicyCenter/webapp-public/pull/414 for relevant changes. If the JS changes look good, please merge and have a look. we should discuss how you will test since you need the updated changes to deploy to try this out. One thing to look at is that in webapp/apps/taxbrain/tests/, there are two files `response_year_0.json` and `response_year_1.json` that you could use as mock data to try out the changes.

**Comment by talumbau** [comment]
I think this is now ready

**Comment by talumbau** [comment]
added code to make sure old reform results pages will still work.

**Pull request merged**
