### PR TITLE
Issue 71: Centering the heading "FROM THE LAB"

### PR DESCRIPTION
**Pull request by johneo**
Addresses issue #71. See the issue for the screenshot.

### CODE REVIEW

**Comment by johneo** [comment]
@talumbau should this be put on ice?

**Comment by talumbau** [comment]
No, or at least, I'm not sure. It turns out we also have https://github.com/OpenSourcePolicyCenter/webapp-public/pull/93 which is another fix for the issue. I'm not sure which is the better one to choose. What do you think?

**Comment by johneo** [comment]
#93 looks good, it centers the heading without adding the extra gap that this one does. Also, it seems to do some code cleanup.

**Comment by talumbau** [comment]
closing in favor of #93

**Pull request closed without merging**
