### PR TITLE
Move btax to conda-requirements.

### PR DESCRIPTION
**Pull request by brittainhard**

### CODE REVIEW

**Comment by PeterDSteinberg** [comment]
How is ogusa installed now?  We should also fix OG-USA install in this PR.

**Comment by brittainhard** [comment]
Not sure. I'll take a look.

**Comment by brittainhard** [comment]
@PeterDSteinberg i dont see it anywhere that ogusa is installed in webapp

**Comment by PeterDSteinberg** [comment]
ok - that's right (regarding OG-USA).  I think we can merge this PR, then.

**Pull request merged**
