### PR TITLE
Form Accordions (WIP)

### LINKED ISSUE #417: Group TB (and CCC) inputs into an accordion menu
Over at https://github.com/open-source-economics/Tax-Calculator/issues/1074#issuecomment-261808528, @feenberg said:

> Perhaps the TB web page could have expandable sections, where you could select a section to expose the parameters available to set, and perhaps subsections that could be expanded recursively.

This seems like a good idea to me too. 

@talumbau and @brendancol, do you have any feedback before I add this to a milestone? Is there a relatively simple way to do this?

### PR DESCRIPTION
**Pull request by brittainhard**
Closes #417

### CODE REVIEW

**Comment by MattHJensen** [comment]
Should I review this on the test app?

**Comment by brittainhard** [comment]
@MattHJensen i'm taking some time off today. My plan is to merge this with the checkbox fixes into one PR, since a lot of issues in this effect issues in the checkbox PR.

**Comment by MattHJensen** [comment]
Sounds good.

**Comment by brittainhard** [comment]
Closing. Merging with #551

**Pull request closed without merging**
