### PR TITLE
Adds reset button with same styling as submit

### LINKED ISSUE #379: Add "Reset Parameters" button.
In Chrome it is easy to reset all input parameters by refreshing the page. In Firefox, however, a refresh does not clear out existing parameters. A "Reset Parameters" button would solve this problem. It could go right above the start year indicator and would just need to link to www.ospc.org/taxbrain. As for styling, a simple hyperlink would be fine to begin with. 

Matt should notify John Sabelhaus when it is complete.

### PR DESCRIPTION
**Pull request by talumbau**
resolves #379

### CODE REVIEW

**Comment by talumbau** [comment]
This is what the button looks like:

screen shot 2016-11-08 at 5 57 07 pm

We can change the styling if desired but would need @brendancol to modify the CSS. This just uses  `type=reset` on HTML input tag which is designed to do what is requested in #379 (clear out input on all forms).

**Comment by talumbau** [comment]
cc @MattHJensen

**Comment by talumbau** [comment]
also resolves #311 

screen shot 2016-11-08 at 7 57 07 pm

cc @MattHJensen 

the flatblocks needs are `home_ccc_subtitle` and `home_ccc_blurb`

**Comment by MattHJensen** [comment]
@talumbau, can we make this generate a pop up like:

image

Except with "Reset Parameters" substituting for "Change Start Year"

**Comment by talumbau** [comment]
currently, clicking this button just wipes out the values in the boxes. Popping up the modal seems to me to be calling a JS function with the `onclick` attribute of the new button. Now sure how to do this because the modal pop-up code for selecting a year appears to be done with anonymous JS functions in `static/js/taxbrain.js`. Assigning to @brendancol to finish up.

**Comment by MattHJensen** [comment]
> the flatblocks needed are home_ccc_subtitle and home_ccc_blurb

Done.

**Comment by talumbau** [comment]
Reset parameters button now looks like:

screen shot 2016-11-18 at 2 42 45 pm

**Comment by talumbau** [comment]
cc @MattHJensen

**Comment by MattHJensen** [comment]
+1

On Nov 18, 2016, at 3:43 PM, T.J. Alumbaugh <notifications@github.com<mailto:notifications@github.com>> wrote:


cc @MattHJensen<https://github.com/MattHJensen>

**Pull request merged**
